Repository ministryofjustice/opg-digideps, pull requests merged in 2023-01, with the labels that each got.

#1088 Remove Ste from Cloud 9
  shared/.terraform.lock.hcl
  shared/variables.tf
Labels: infrastructure

#1077 sec fix for missing paths
  .circleci/config.yml
Labels: pipelines

#1090 Remove forced security updates now mainline alpine image is updated
  api/Dockerfile
Labels: api

#1089 DDPB-4595 - Balance Mismatches Report
  docs/queries/Balance Mismatches Report.sql
  docs/queries/QUERIES.md
Labels: documentation
