Repository ministryofjustice/opg-digideps, pull requests merged in 2023-11, with the labels that each got.

#1444 DDPB-4856 add pr number to PRs
  .github/workflows/workflow-destroy-on-merge.yml
  .github/workflows/workflow-path-to-live.yml
  .github/workflows/workflow-pull-request-dependabot-app.yml
  .github/workflows/workflow-pull-request-dependabot-terraform.yml
  .github/workflows/workflow-pull-request-path.yml
  terraform/environment/scripts/destroy_workspace.sh
  terraform/environment/scripts/workspace_cleanup.sh
Labels: infrastructure, pipelines

#1454 DDPB-4857 - Correction to the display of submitted reports and NDR
  client/app/templates/Ndr/Ndr/_review_buttons.html.twig
  client/app/templates/Report/Report/_review_buttons.html.twig
Labels: client-service

#1443 DDPB-4846 - re-add XSS waf rule
  terraform/account/waf.tf
Labels: infrastructure

#1457 Revert "DDPB-4846 - re-add XSS waf rule (#1443)"
  terraform/account/waf.tf
Labels: infrastructure

#1452 DDPB 4809 - New Summary page for Money In & Out
  Makefile
  api/app/src/Entity/Report/Report.php
  client/app/src/Controller/Report/MoneyInController.php
  client/app/src/Controller/Report/MoneyInShortController.php
  client/app/src/Controller/Report/MoneyOutController.php
  client/app/src/Controller/Report/MoneyOutShortController.php
  client/app/src/Entity/Report/Report.php
  client/app/templates/Report/MoneyIn/_list_new.html.twig
  client/app/templates/Report/MoneyIn/new_summary.html.twig
  client/app/templates/Report/MoneyInShort/_answers_new.html.twig
  client/app/templates/Report/MoneyInShort/new_summary.html.twig
  client/app/templates/Report/MoneyOut/_list_new.html.twig
  client/app/templates/Report/MoneyOut/new_summary.html.twig
  client/app/templates/Report/MoneyOutShort/_answers_new.html.twig
  client/app/templates/Report/MoneyOutShort/new_summary.html.twig
  client/app/translations/report-money-short.en.yml
  client/app/translations/report-money-transaction.en.yml
Labels: client-service, api-service

#1442 DDPB-3703 move to graviton based single cache resource per account
  api/app/api.env
  api/app/config/parameters.yml.dist
  api/app/config/services.yml
  api/app/config/services_test.yml
  api/app/src/Controller/AuthController.php
  api/app/src/Security/RedisUserProvider.php
  api/app/src/Service/BruteForce/AttemptsInTimeChecker.php
  api/app/src/Service/BruteForce/AttemptsIncrementalWaitingChecker.php
  api/app/tests/Unit/Service/Auth/UserProviderTest.php
  api/docker/app/confd/conf.d/parameters.hml.toml
  api/docker/app/confd/templates/parameters.yml.tmpl
  client/app/admin.env
  client/app/config/packages/snc_redis.yml
  client/app/config/parameters.yml.dist
  client/app/config/services.yml
  client/app/frontend.env
  client/app/src/Command/ProcessLayCSVCommand.php
  client/app/src/Command/ProcessOrgCSVCommand.php
  client/app/src/Controller/Admin/IndexController.php
  client/app/src/Service/Availability/RedisAvailability.php
  client/app/src/Service/Client/TokenStorage/RedisStorage.php
  client/app/tests/phpunit/Service/Client/TokenStorage/RedisStorageTest.php
  client/docker/app/confd/conf.d/parameters.hml.toml
  client/docker/app/confd/templates/parameters.yml.tmpl
  docker-compose.yml
  terraform/account/elasticache.tf
  terraform/account/elasticache_parameters.tf
  terraform/environment/admin_service.tf
  terraform/environment/admin_sg.tf
  terraform/environment/api_service.tf
  terraform/environment/api_sg.tf
  terraform/environment/check_csv_uploaded.tf
  terraform/environment/dns_private.tf
  terraform/environment/elasticache.tf
  terraform/environment/front_service.tf
  terraform/environment/front_sg.tf
  terraform/environment/integration_test_v2.tf
  terraform/environment/smoke_test.tf
  terraform/environment/sync_to_sirius_checklists.tf
  terraform/environment/sync_to_sirius_documents.tf
Labels: infrastructure, client-service, api-service

#1461 DDLS-40 move to shared cache part2
  terraform/environment/admin_sg.tf
  terraform/environment/api_sg.tf
  terraform/environment/dns_private.tf
  terraform/environment/elasticache.tf
  terraform/environment/front_sg.tf
Labels: infrastructure

#1463 DDLS-40b remove old elasticache
  terraform/environment/admin_sg.tf
  terraform/environment/api_elasticache.tf
  terraform/environment/api_sg.tf
  terraform/environment/dashboard.tf
  terraform/environment/front_sg.tf
  terraform/environment/frontend_shared_elasticache.tf
Labels: infrastructure

#1465 Ddls-58 Handle 404s better
  Makefile
  client/app/config/services.yml
  client/app/src/EventListener/NotFoundExceptionListener.php
Labels: client-service

#1464 Ddls-56 Improve WAF rules to capture some common patterns that should not be allowed
  terraform/account/waf.tf
Labels: infrastructure

#1466 DDLS-59 resubmit resubmittable documents on a nightly basis
  api/app/src/Command/ResyncResubmittableErrorDocuments.php
  api/app/src/Repository/DocumentRepository.php
  api/app/tests/Unit/Entity/Repository/DocumentRepositoryTest.php
  terraform/account/elasticache.tf
  terraform/account/terraform.tfvars.json
  terraform/account/variables.tf
  terraform/environment/scheduled_events.tf
  terraform/environment/scheduled_events_checks.tf
Labels: infrastructure, api-service

#1469 DDLS-69 fix snapshot window conflict
  terraform/account/elasticache.tf
Labels: infrastructure

#1468 DDLS-68 add default tags to resources
  terraform/account/provider.tf
  terraform/environment/provider.tf
Labels: infrastructure

#1472 DDLS-54 add secret part 1
  terraform/account/secrets.tf
Labels: infrastructure

#1471 DDLS-8 & DDLS-16 - Checklist & PDF changes for No Money In & Out
  client/app/src/Controller/Admin/Client/ReportController.php
  client/app/src/Controller/Report/ReportController.php
  client/app/src/Service/ReportSubmissionService.php
  client/app/templates/Admin/Client/Report/new_checklist.html.twig
  client/app/templates/Admin/Client/Report/partials/_new_money-in-and-out.html.twig
  client/app/templates/Admin/Client/Report/partials/_new_money-summaries.html.twig
  client/app/templates/Report/Formatted/Accounts/_new_money_in_out.html.twig
  client/app/templates/Report/Formatted/Accounts/_new_money_in_out_short.html.twig
  client/app/templates/Report/Formatted/new_formatted_body.html.twig
  client/app/templates/Report/Formatted/new_formatted_standalone.html.twig
  client/app/templates/Report/Report/_new_pdf_download_link.html.twig
  client/app/templates/Report/Report/new_review.html.twig
Labels: client-service

#1476 DDLS-7A: Extension of DDLS-7 branch (Money In)
  client/app/templates/Report/MoneyInShort/_answers.html.twig
Labels: client-service
